# Generated by Django 5.2.11 on 2026-02-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('AD', 'Admin'), ('MS', 'Marketing/Sales')], max_length=5)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('country', models.CharField(max_length=255, null=True)),
                ('user_type', models.CharField(default='USER', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
